### ISSUE TITLE
SingularMatrix error when Copula can be fitted with alternative start values

### ISSUE THREAD

**Issue by jkfm** [DanielBok/copulae#10]
Hi,

When fitting a Gaussian and Student Copula, I quite often encounter the np.linalg.LinAlgError: singular matrix.

I suspect this could be solved with other initial parameters, because my current workaround is to try to fit the Copula with a randomly selected subset of the data and then use the estimates as starting values for the original dataset. Until now, this always worked. 

Maybe there is an easy fix for this?

**Comment by DanielBok** [comment]
Hello, 

I have some suspicion where the error is coming from. But if possible, could you attach the stack trace?

**Comment by jkfm** [comment]
Sure, here you go:

`Traceback (most recent call last):
  File "/opt/next/master-thesis-risk/Code/hedging_risk/abstract.py", line 60, in fit
    self.copula.fit(data=self.data_array, est_var=True)
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/copulae/copula/base.py", line 81, in fit
    CopulaEstimator(self, data, x0=x0, method=method, est_var=est_var, verbose=verbose, optim_options=optim_options)
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/copulae/copula/estimator.py", line 66, in __init__
    self.fit()  # fit the copula
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/copulae/copula/estimator.py", line 72, in fit
    self._verbose).fit(m)
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/copulae/copula/est_max_likelihood.py", line 60, in fit
    res = self._optimize()
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/copulae/copula/est_max_likelihood.py", line 108, in _optimize
    return minimize(self.copula_log_lik, self.initial_params, **self.optim_options)
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 611, in minimize
    constraints, callback=callback, **options)
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/scipy/optimize/slsqp.py", line 379, in _minimize_slsqp
    fx = func(x)
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 293, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/copulae/copula/est_max_likelihood.py", line 103, in copula_log_lik
    return -self.copula.log_lik(self.data)
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/copulae/elliptical/abstract.py", line 43, in log_lik
    return super().log_lik(data)
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/copulae/copula/base.py", line 194, in log_lik
    return self.pdf(self.pobs(data), log=True).sum()
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/copulae/utility/utils.py", line 36, in internal
    res = np.asarray(f(cls, x, *args, **kwargs))
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/copulae/elliptical/gaussian.py", line 82, in pdf
    d = mvn.logpdf(q, cov=sigma) - norm.logpdf(q).sum(1)
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/scipy/stats/_multivariate.py", line 487, in logpdf
    psd = _PSD(cov, allow_singular=allow_singular)
  File "/home/johanneskaufmann/.local/share/virtualenvs/Code-Qd3Mt1KR/lib/python3.6/site-packages/scipy/stats/_multivariate.py", line 159, in __init__
    raise np.linalg.LinAlgError('singular matrix')
numpy.linalg.LinAlgError: singular matrix`

**Comment by DanielBok** [comment]
Hello, sorry I haven't gotten back on the issue for a while. I've done some tests to try and replicate the issue but I think the solution lies mainly in the data treatment (pre-processing) prior to fitting with the copula.

This error will occur if at least one column of your data is a linear combination (or extremely close) of other columns. So something like the below will trigger it.

```python
arr = np.random.normal(size=(100, 3))
arr[:, -1] = arr[:, 0] * 0.5
```

**Comment by jkfm** [comment]
No problem. That sounds like itihht be the cause, I'm pretty sure that there are no linear combinations (two dimension empirical data), but there are often 0-values in one of the series, so your explanation makes sense.
