### ISSUE TITLE
Python 3.6 not supported?

### ISSUE THREAD

**Issue by Nishan-Pradhan** [DanielBok/copulae#48]
Hi, 

I am getting the following error message when trying to `pip install copulae`:

```
Collecting copulae
  Using cached https://files.pythonhosted.org/packages/66/e4/d727292d72ed1319bea836b0cdbfc304d1382f4cdf8d40017a57bbf9b0e9/copulae-0.7.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=1.5 (from copulae)
  Using cached https://files.pythonhosted.org/packages/bb/bb/944f559d554df6c9adf037aa9fc982a9706ee0e96c0d5beac701cb158900/scipy-1.7.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ivoevpoe/scipy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.7 required.")
    RuntimeError: Python version >= 3.7 required.
```

This is contradictory to the docs - https://copulae.readthedocs.io/en/latest/getting-started.html which state 3.6 will be supported until 23 December 2021.

How can this be fixed? Thanks

**Comment by DanielBok** [comment]
Ah.. the issue is not copulae. As you can see, the 3.6 wheel for copulae exists. The issue is that scipy stopped supporting 3.6 since their 1.6 release. 

One way to solve this is to install scipy first. Then install copulae.

**Comment by Nishan-Pradhan** [comment]
Thanks for your response, I managed to install `copulae` with that method but getting unexpected errors now, perhaps due to my current module versions? 

Does this example code still work? 

```
from copulae.datasets import load_residuals, load_marginal_data
from copulae import GaussianCopula, StudentCopula

residuals = load_residuals()
residuals.head()

_, ndim = residuals.shape
g_cop = GaussianCopula(dim=ndim)  # initializing the copula
g_cop.fit(residuals)
```

I am getting a `ValueError` like below: 

```
 File "<ipython-input-54-d2563863>", line 9, in <module>
    g_cop.fit(residuals)
  File "/users/is/npr/pyenvs/search/lib/python3.6/site-packages/copulae/copula/base.py", line 134, in fit
    elif np.any((data < 0) | (data > 1)):
  File "/lib/python3.6/site-packages/pandas-0.22.0-linux-x86_64.egg/pandas/core/generic.py", line 1121, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by DanielBok** [comment]
I did the following and it worked okay

```sh
conda create -n py36 python=3.6 copulae
conda activate py36
python
```

```python
from copulae.datasets import load_residuals, load_marginal_data
from copulae import GaussianCopula, StudentCopula

residuals = load_residuals()
residuals.head()

_, ndim = residuals.shape
g_cop = GaussianCopula(dim=ndim)  # initializing the copula
g_cop.fit(residuals)
```
![image](https://user-images.githubusercontent.com/9165086/127413502-50db5e3d-80a9-4286-bd40-1ed2edf6d273.png)

**Comment by DanielBok** [comment]
It looks like an error raised by pandas. Try getting your packages up to requirements first

```
requirements = [
    'numpy >=1.19',
    'pandas >=1.1',
    'scikit-learn >=0.23',
    'scipy >=1.5',
    'statsmodels >=0.12.1',
    "typing-extensions >=3.7.4.3; python_version < '3.8'",
    "wheel >=0.36",
    'wrapt >=1.12'
]
```
